/**
 * Environment file writer
 */

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import type { SetupConfiguration, BlueskyCredentials, AnthropicCredentials } from '@ngaj/shared';
import { generateLoginSecret } from '@ngaj/shared';

const ENV_FILE_PATH = '/data/.env';

/**
 * Result of writing the .env file
 */
export interface WriteEnvResult {
  loginSecret: string;
}

/**
 * Write credentials to .env file
 * @returns The generated login secret for display to the user
 */
export async function writeEnvFile(config: SetupConfiguration): Promise<WriteEnvResult> {
  // Generate login secret for authentication
  const loginSecret = generateLoginSecret();

  const lines: string[] = [
    '# ngaj Configuration',
    `# Generated by setup wizard on ${config.completedAt.toISOString()}`,
    '',
  ];

  // Platform credentials
  for (const cred of config.platformCredentials) {
    if (cred.platform === 'bluesky') {
      const bluesky = cred as BlueskyCredentials;
      lines.push('# Bluesky Credentials');
      lines.push(`BLUESKY_HANDLE=${bluesky.handle}`);
      lines.push(`BLUESKY_APP_PASSWORD=${bluesky.appPassword}`);
      lines.push('');
    }
  }

  // AI credentials
  if (config.aiCredentials.provider === 'anthropic') {
    const anthropic = config.aiCredentials as AnthropicCredentials;
    lines.push('# Anthropic (Claude) API');
    lines.push(`ANTHROPIC_API_KEY=${anthropic.apiKey}`);
    lines.push('');
  }

  // Database configuration (defaults for Docker)
  lines.push('# Database Configuration');
  lines.push('MONGODB_URI=mongodb://mongodb:27017/ngaj');
  lines.push('CHROMA_URL=http://chromadb:8000');
  lines.push('');

  // Application settings
  lines.push('# Application Settings');
  lines.push('PORT=3000');
  lines.push('NODE_ENV=production');
  lines.push('');

  // Authentication
  lines.push('# Authentication');
  lines.push(`LOGIN_SECRET=${loginSecret}`);

  const content = lines.join('\n');

  // Ensure directory exists
  const dir = dirname(ENV_FILE_PATH);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  writeFileSync(ENV_FILE_PATH, content, 'utf-8');

  return { loginSecret };
}
