/**
 * Application Launcher Test Fixtures
 *
 * Test data for network access display and application launcher testing.
 * @see ADR-011: Installation and Setup Architecture (Sections 6 and 7)
 * @see 010-network-access-display-handoff.md
 * @see 012-application-launcher-handoff.md
 */

// ============================================================================
// LAN IP Detection Fixtures
// ============================================================================

/**
 * Valid LAN IP addresses for testing
 */
export const validLanIPs = {
  wifiIP: '192.168.1.42',
  ethernetIP: '192.168.1.100',
  vpnIP: '10.8.0.5',
  alternateWifi: '192.168.0.10',
  corporateNetwork: '10.0.1.50',
};

/**
 * Invalid/excluded IP addresses that should be filtered out
 */
export const invalidIPs = {
  localhost: '127.0.0.1',
  localhostAlternate: '127.0.0.2',
  apipa: '169.254.1.1', // Automatic Private IP Addressing (no DHCP)
  apipaAlternate: '169.254.100.50',
};

/**
 * macOS network interface mock data
 */
export const macOSInterfaceMocks = {
  /** WiFi connected on en0 */
  wifiConnected: {
    en0: '192.168.1.42',
    en1: null,
  },
  /** Ethernet only on en1 */
  ethernetOnly: {
    en0: null,
    en1: '192.168.1.100',
  },
  /** Both WiFi and Ethernet connected */
  bothConnected: {
    en0: '192.168.1.42',
    en1: '192.168.1.100',
  },
  /** No network interfaces */
  noNetwork: {
    en0: null,
    en1: null,
  },
  /** VPN active (returns VPN IP) */
  vpnActive: {
    en0: '10.8.0.5',
    en1: null,
  },
};

/**
 * Windows network interface mock data
 */
export const windowsInterfaceMocks = {
  /** WiFi connected */
  wifiConnected: [
    {
      IPAddress: '192.168.1.42',
      InterfaceAlias: 'Wi-Fi',
      PrefixOrigin: 'Dhcp',
    },
  ],
  /** Ethernet only */
  ethernetOnly: [
    {
      IPAddress: '192.168.1.100',
      InterfaceAlias: 'Ethernet',
      PrefixOrigin: 'Manual',
    },
  ],
  /** Both WiFi and Ethernet (WiFi should be preferred) */
  bothConnected: [
    {
      IPAddress: '192.168.1.42',
      InterfaceAlias: 'Wi-Fi',
      PrefixOrigin: 'Dhcp',
    },
    {
      IPAddress: '192.168.1.100',
      InterfaceAlias: 'Ethernet',
      PrefixOrigin: 'Manual',
    },
  ],
  /** No valid network (APIPA only) */
  apipaOnly: [
    {
      IPAddress: '169.254.1.1',
      InterfaceAlias: 'Wi-Fi',
      PrefixOrigin: 'WellKnown',
    },
  ],
  /** Localhost only */
  localhostOnly: [
    {
      IPAddress: '127.0.0.1',
      InterfaceAlias: 'Loopback',
      PrefixOrigin: 'Manual',
    },
  ],
  /** No network interfaces */
  noNetwork: [],
  /** VPN + WiFi (should return WiFi) */
  vpnPlusWifi: [
    {
      IPAddress: '10.8.0.5',
      InterfaceAlias: 'VPN Client',
      PrefixOrigin: 'Manual',
    },
    {
      IPAddress: '192.168.1.42',
      InterfaceAlias: 'Wi-Fi',
      PrefixOrigin: 'Dhcp',
    },
  ],
};

// ============================================================================
// Docker Detection Fixtures
// ============================================================================

/**
 * Docker info command mock responses
 */
export const dockerInfoMocks = {
  /** Docker running and healthy */
  running: {
    exitCode: 0,
    output: 'Server: Docker Desktop\n...',
  },
  /** Docker daemon not running */
  notRunning: {
    exitCode: 1,
    output: 'Cannot connect to the Docker daemon...',
  },
  /** Docker not installed */
  notInstalled: {
    exitCode: 127,
    output: 'docker: command not found',
  },
};

/**
 * Docker compose command mock responses
 */
export const dockerComposeMocks = {
  /** Services started successfully */
  upSuccess: {
    exitCode: 0,
    output: 'Container ngaj-backend-1  Started\nContainer ngaj-mongodb-1  Started',
  },
  /** Port conflict error */
  portConflict: {
    exitCode: 1,
    output: 'Error response from daemon: port is already allocated',
  },
  /** Already running (idempotent) */
  alreadyRunning: {
    exitCode: 0,
    output: 'Container ngaj-backend-1  Running\nContainer ngaj-mongodb-1  Running',
  },
  /** Down success */
  downSuccess: {
    exitCode: 0,
    output: 'Container ngaj-backend-1  Stopped',
  },
};

// ============================================================================
// Login Code / .env Fixtures
// ============================================================================

/**
 * Sample .env file contents
 */
export const envFileMocks = {
  /** Valid .env with LOGIN_SECRET */
  validWithLoginSecret: `# ngaj Configuration
# Generated by setup wizard on 2026-01-24T12:00:00Z

# Bluesky Credentials
BLUESKY_HANDLE=@testuser.bsky.social
BLUESKY_APP_PASSWORD=xxxx-xxxx-xxxx-xxxx

# Anthropic (Claude) API
ANTHROPIC_API_KEY=sk-ant-api03-test-key-12345

# Authentication
LOGIN_SECRET=A1B2-C3D4-E5F6-G7H8

# Database Configuration
MONGODB_URI=mongodb://mongodb:27017/ngaj
CHROMA_URL=http://chromadb:8000

# Application Settings
PORT=3000
NODE_ENV=production`,

  /** Valid .env without LOGIN_SECRET */
  validWithoutLoginSecret: `# ngaj Configuration
BLUESKY_HANDLE=@testuser.bsky.social
BLUESKY_APP_PASSWORD=xxxx-xxxx-xxxx-xxxx
ANTHROPIC_API_KEY=sk-ant-api03-test-key-12345
MONGODB_URI=mongodb://mongodb:27017/ngaj
PORT=3000`,

  /** Malformed .env (invalid format) */
  malformed: `This is not a valid .env file
LOGIN_SECRET without equals sign
= missing key`,

  /** Empty .env file */
  empty: '',
};

/**
 * Expected LOGIN_SECRET values
 */
export const loginSecretMocks = {
  valid: 'A1B2-C3D4-E5F6-G7H8',
  validAlternate: 'X9Y8-Z7W6-V5U4-T3S2',
  empty: '',
};

// ============================================================================
// Health Check Fixtures
// ============================================================================

/**
 * Backend health check mock responses
 */
export const healthCheckMocks = {
  /** Healthy backend */
  healthy: {
    status: 200,
    body: { status: 'ok', version: '0.1.0' },
  },
  /** Unhealthy backend */
  unhealthy: {
    status: 503,
    body: { status: 'error', message: 'Database connection failed' },
  },
  /** Timeout (no response) */
  timeout: null,
};

// ============================================================================
// Terminal Output Fixtures
// ============================================================================

/**
 * Expected terminal output patterns
 */
export const terminalOutputPatterns = {
  /** Backend running message */
  backendRunning: '✓ Backend running',

  /** Local access URL pattern */
  localAccess: /Local access:\s+http:\/\/localhost:3000/,

  /** Network access URL pattern */
  networkAccess: /Network access:\s+http:\/\/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:3000/,

  /** Mobile hint message */
  mobileHint: '(Use this URL from your mobile device on the same WiFi)',

  /** Login code display pattern */
  loginCode: /Login code:\s+[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}-[A-Z0-9]{4}/,

  /** Startup messages */
  startingDocker: 'Starting Docker Desktop...',
  waitingForDocker: 'Waiting for Docker daemon...',
  dockerReady: '✓ Docker is ready',
  waitingForServices: 'Waiting for services...',

  /** Shutdown messages */
  stoppingNgaj: 'Stopping ngaj...',
  ngajStopped: '✓ ngaj stopped',
};

/**
 * Full terminal output examples
 */
export const terminalOutputExamples = {
  /** Output with network available */
  withNetwork: `✓ Backend running

  Local access:   http://localhost:3000
  Network access: http://192.168.1.42:3000
  (Use this URL from your mobile device on the same WiFi)`,

  /** Output without network (localhost only) */
  withoutNetwork: `✓ Backend running

  Local access:   http://localhost:3000`,

  /** Full output with login code */
  fullWithLoginCode: `✓ Backend running

  Local access:   http://localhost:3000
  Network access: http://192.168.1.42:3000
  (Use this URL from your mobile device on the same WiFi)

  Login code: A1B2-C3D4-E5F6-G7H8
  (Enter this code when prompted in your browser)`,

  /** Cold start output */
  coldStart: `🚀 Starting ngaj...

Starting Docker Desktop...
Waiting for Docker daemon...
✓ Docker is ready

Waiting for services...
✓ Backend running

Dashboard:    http://192.168.1.42:3000
Login code:   A1B2-C3D4-E5F6-G7H8

(Use login code from any device on your WiFi)

Press Ctrl+C to stop ngaj`,
};

// ============================================================================
// File System Fixtures
// ============================================================================

/**
 * macOS app bundle paths
 */
export const macOSPaths = {
  appBundle: '/Applications/ngaj.app',
  launcher: '/Applications/ngaj.app/Contents/MacOS/ngaj-launcher',
  infoPlist: '/Applications/ngaj.app/Contents/Info.plist',
  iconFile: '/Applications/ngaj.app/Contents/Resources/icon.icns',
  startScript: '~/.ngaj/scripts/ngaj-start.sh',
  envFile: '~/.ngaj/.env',
  dataDir: '~/.ngaj/data',
};

/**
 * Windows paths
 */
export const windowsPaths = {
  startMenuShortcut: '%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\ngaj.lnk',
  startScript: '%LOCALAPPDATA%\\ngaj\\scripts\\ngaj-start.ps1',
  iconFile: '%ProgramFiles%\\ngaj\\resources\\ngaj.ico',
  envFile: '%LOCALAPPDATA%\\ngaj\\.env',
  dataDir: '%LOCALAPPDATA%\\ngaj\\data',
};

/**
 * Info.plist expected values
 */
export const infoPlistExpected = {
  CFBundleExecutable: 'ngaj-launcher',
  CFBundleIconFile: 'icon',
  CFBundleIdentifier: 'com.ngaj.launcher',
  CFBundleName: 'ngaj',
  CFBundleDisplayName: 'ngaj',
  CFBundlePackageType: 'APPL',
  CFBundleShortVersionString: '0.1.0',
  LSMinimumSystemVersion: '10.15',
  NSHighResolutionCapable: true,
};

// ============================================================================
// Error Scenario Fixtures
// ============================================================================

/**
 * Error scenarios for testing
 */
export const errorScenarios = {
  /** Docker Desktop not installed */
  dockerNotInstalled: {
    message: 'Docker not found. Please install Docker Desktop.',
    exitCode: 1,
  },
  /** Health check timeout */
  healthCheckTimeout: {
    message: 'Services failed to start. Check logs.',
    timeout: 60000,
  },
  /** Port conflict */
  portConflict: {
    message: 'Port 3000 is already in use',
    exitCode: 1,
  },
  /** Docker daemon timeout */
  dockerDaemonTimeout: {
    message: 'Docker daemon failed to start within 60 seconds',
    timeout: 60000,
  },
};

// ============================================================================
// Factory Functions
// ============================================================================

/**
 * Create mock network interface data for macOS
 */
export function createMacOSNetworkMock(
  en0IP: string | null,
  en1IP: string | null
): Record<string, string | null> {
  return { en0: en0IP, en1: en1IP };
}

/**
 * Create mock network interface data for Windows
 */
export function createWindowsNetworkMock(
  interfaces: Array<{
    ip: string;
    alias: string;
    origin: 'Dhcp' | 'Manual' | 'WellKnown';
  }>
): Array<{ IPAddress: string; InterfaceAlias: string; PrefixOrigin: string }> {
  return interfaces.map((iface) => ({
    IPAddress: iface.ip,
    InterfaceAlias: iface.alias,
    PrefixOrigin: iface.origin,
  }));
}

/**
 * Create mock .env file content
 */
export function createEnvFileMock(options: {
  loginSecret?: string;
  blueskyHandle?: string;
  anthropicKey?: string;
}): string {
  const lines: string[] = ['# ngaj Configuration'];

  if (options.blueskyHandle) {
    lines.push(`BLUESKY_HANDLE=${options.blueskyHandle}`);
    lines.push('BLUESKY_APP_PASSWORD=xxxx-xxxx-xxxx-xxxx');
  }

  if (options.anthropicKey) {
    lines.push(`ANTHROPIC_API_KEY=${options.anthropicKey}`);
  }

  if (options.loginSecret) {
    lines.push(`LOGIN_SECRET=${options.loginSecret}`);
  }

  lines.push('MONGODB_URI=mongodb://mongodb:27017/ngaj');
  lines.push('PORT=3000');

  return lines.join('\n');
}

/**
 * Create mock terminal output
 */
export function createTerminalOutput(options: {
  lanIP?: string;
  loginCode?: string;
  showNetworkHint?: boolean;
}): string {
  const lines: string[] = ['✓ Backend running', ''];

  lines.push('  Local access:   http://localhost:3000');

  if (options.lanIP) {
    lines.push(`  Network access: http://${options.lanIP}:3000`);
    if (options.showNetworkHint !== false) {
      lines.push('  (Use this URL from your mobile device on the same WiFi)');
    }
  }

  if (options.loginCode) {
    lines.push('');
    lines.push(`  Login code: ${options.loginCode}`);
    lines.push('  (Enter this code when prompted in your browser)');
  }

  return lines.join('\n');
}
